### ISSUE TITLE
Replace `getPokemonSpeciesByName` with `getPokemonByName`

### ISSUE THREAD

**Issue by ainsleyrutterford** [benparanrutterford/poke-info#6]
If we replace `getPokemonSpeciesByName` with `getPokemonByName`, we get a `Pokemon` type as opposed to a `PokemonSpecies` type. With the `Pokemon` type, we get [access to different attributes](https://github.com/PokeAPI/pokedex-promise-v2/blob/master/types/index.d.ts#L1233), including the Pokémon's types (which we can later use to calculate a Pokémon's weakness).

**Comment by benparanrutterford** [comment]
#5
