### ISSUE TITLE
Use a type assertion on the return value of `getPokemonByName`

### ISSUE THREAD

**Issue by ainsleyrutterford** [benparanrutterford/poke-info#7]
At the moment, we get a return type of `Pokemon | Pokemon[]`. This means that we will not have any autocomplete on the return value as VSCode will not know if we are dealing with a `Pokemon` or `Pokemon[]`. Since we know that we are only passing in one name to `getPokemonByName`, we know that the return type will definitely be `Pokemon`, so we can use a type assertion to tell TypeScript.

Type assertions are done using the `as` keyword, and are explained [here](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions). In general, it shouldn't be necessary to use type assertions, but in this case I think that we need to due to the implementation of `getPokemonByName` in `pokedex-promise-v2`.

(**Hint:** you may need to import the `Pokemon` type at the top of the file. VSCode auto-import will probably do the job for you! Otherwise, you can find the type [here](https://github.com/PokeAPI/pokedex-promise-v2/blob/master/types/index.d.ts#L1233).)

**Comment by benparanrutterford** [comment]
#8
